### PR TITLE
Adds test for TopNextSongs pipeline and gets checkstyle in order.

### PR DESCRIPTION
**Pull request by hougs**

### CODE REVIEW

**Comment by hougs** [comment]
@kryzthov

**Comment by kimballa** [comment]
please enable email to eng@ on on the jenkins nightly-kiji-music project after pushing this fix.

**Comment by kimballa** [comment]
(that 'close' was accidental)

**Comment by kryzthov** [comment]
ac3dd92bd71d6d0f3f1462c8514406a5d95980f7

**Comment by kryzthov** [comment]
Updated some documentation and minor typos.

**Pull request closed without merging**
