### PR TITLE
KIJIMR-80. Updates imports to be consistent with Kiji MapReduce package ...

### PR DESCRIPTION
**Pull request by sqrl**
...shuffle.

To be pushed after https://github.com/kijiproject/kiji-mapreduce/pull/56

Testing done: mvn clean verify after installing kijimr-80 Kiji MapReduce and Kiji MapReduce Lib.

### CODE REVIEW

**Comment by sqrl** [comment]
@lsheng can you take a look? @jhlch and @kryzthov should also look to confirm that this is satisfactory.

**Comment by lsheng** [comment]
+! looks good. Push pending on minimal changes possibly required about the naming of KijiMapReduceJobBuilder.
Merge pull request

**Comment by lsheng** [comment]
https://github.com/kijiproject/kiji-music/commit/0530ea3ba9fe76d22c0b556cf144d28047ed104a

**Comment by hougs** [comment]
Looks fine to me. +1

**Pull request closed without merging**
